// @vitest-environment node
//
// Wave 0 (test-first RED) contract for the DOCX runtime. Unlike pdf.test.ts we do
// NOT mock mammoth: it parses .docx on the main thread under Node unmodified (jszip
// + @xmldom), so we exercise the REAL parser against the real fixtures generated by
// scripts/gen-docx-fixtures.mjs. This import of ./docx is EXPECTED to be unresolved
// until 03-02 lands extractDocx/classifyDocxError — that unresolved module is the
// correct Wave 0 RED state.
//
// Fixtures (test/fixtures/*):
//   - sample.docx    paragraph + 2-item list + 2x2 table  -> reflowed paragraphs (D-17)
//   - empty.docx     whitespace-only body                  -> reason 'empty'
//   - not-word.zip   PK-zip without word/document.xml      -> reason 'unsupported'
//   - corrupt.docx   sample truncated past its EOCD record -> reason 'corrupt'
import { describe, it, expect, vi } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { extractDocx, classifyDocxError } from "./docx";

function docxBuffer(name: string, ext = ".docx"): ArrayBuffer {
  const b = readFileSync(resolve(process.cwd(), `test/fixtures/${name}${ext}`));
  return b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength);
}
const liveSignal = () => new AbortController().signal;
const abortedSignal = () => {
  const c = new AbortController();
  c.abort();
  return c.signal;
};

describe("extractDocx — DOCX runtime (INPUT-04, D-16/17/18, PRIV-01)", () => {
  it("extracts a real .docx to reflowed paragraphs incl. list + table text (D-17)", async () => {
    const r = await extractDocx(docxBuffer("sample"), liveSignal());
    expect("ok" in r && r.ok).toBe(true);
    if ("ok" in r && r.ok) {
      const all = r.doc.paragraphs.join(" ");
      expect(all).toContain("Reading helps focus");
      expect(all).toContain("First item");
      expect(all).toContain("Second item");
      expect(all).toContain("R1C1"); // table cells flattened to text
      expect(all).toContain("R2C2");
    }
  });

  it("maps an empty-body .docx to reason:empty", async () => {
    const r = await extractDocx(docxBuffer("empty"), liveSignal());
    expect(r).toEqual({ error: true, reason: "empty" });
  });

  it("maps a non-Word PK-zip to reason:unsupported (real mammoth error)", async () => {
    const r = await extractDocx(docxBuffer("not-word", ".zip"), liveSignal());
    expect(r).toEqual({ error: true, reason: "unsupported" });
  });

  it("maps a corrupt/truncated .docx to reason:corrupt", async () => {
    const r = await extractDocx(docxBuffer("corrupt"), liveSignal());
    expect(r).toEqual({ error: true, reason: "corrupt" });
  });

  it("pins the real jszip corrupt-zip message that classifyDocxError keys on (A3)", async () => {
    // Capture the actual thrown message from the REAL parser so the classifier
    // regex stays anchored to a string mammoth/jszip really produces.
    let thrown = "";
    try {
      const mammoth = await import("mammoth");
      // Mirror extractDocx's dual-key call: the node build reads `buffer`, the
      // browser build reads `arrayBuffer` — pass both so this captures the REAL
      // jszip corrupt-zip error here in the node test env.
      const buf = docxBuffer("corrupt");
      await mammoth.extractRawText({ arrayBuffer: buf, buffer: buf as never });
    } catch (e) {
      thrown = (e as { message?: string })?.message ?? "";
    }
    expect(thrown).not.toBe("");
    expect(classifyDocxError({ message: thrown })).toEqual({ error: true, reason: "corrupt" });
  });

  it("honors an already-aborted signal (resolve-then-discard) -> cancelled", async () => {
    const r = await extractDocx(docxBuffer("sample"), abortedSignal());
    expect(r).toEqual({ error: true, reason: "cancelled" });
  });

  it("makes no network/fetch call during extraction (PRIV-01)", async () => {
    const fetchSpy = vi.fn();
    const original = globalThis.fetch;
    globalThis.fetch = fetchSpy as unknown as typeof fetch;
    try {
      await extractDocx(docxBuffer("sample"), liveSignal());
    } finally {
      globalThis.fetch = original;
    }
    expect(fetchSpy).not.toHaveBeenCalled();
  });
});

describe("classifyDocxError — pure message -> closed taxonomy", () => {
  it("'Could not find main document part' -> unsupported", () => {
    expect(classifyDocxError({ message: "Could not find main document part. Are you sure this is a valid .docx file?" })).toEqual({
      error: true,
      reason: "unsupported",
    });
  });

  it("a central-directory / corrupt-zip message -> corrupt", () => {
    expect(classifyDocxError({ message: "Corrupted zip: can't find end of central directory" })).toEqual({
      error: true,
      reason: "corrupt",
    });
  });

  it("an unrecognized message -> unknown", () => {
    expect(classifyDocxError({ message: "something else entirely" })).toEqual({ error: true, reason: "unknown" });
  });
});
